apiVersion: v2
name: sonarqube
description: SonarQube is an open sourced code quality scanning tool
version: 6.6.1
appVersion: 8.2-community
keywords:
  - coverage
  - security
  - code
  - quality
home: https://www.sonarqube.org/
icon: https://www.sonarqube.org/assets/logo-31ad3115b1b4b120f3d1efd63e6b13ac9f1f89437f0cf6881cc4d8b5603a52b4.svg
sources:
  - https://github.com/SonarSource/docker-sonarqube
maintainers:
  - name: rjkernick
    email: rjkernick@gmail.com
  - name: tsiddique
    email: tsiddique@live.com
dependencies:
- name: postgresql
  version: 8.6.4
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
